# Generated by Django 3.1.6 on 2021-02-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactField',
            new_name='FormField',
        ),
    ]
